/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beginner;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TANDOH
 */
public class Simple_Quiz extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Simple_Quiz() {
        initComponents();

        this.setIconImage(new ImageIcon(getClass().getResource("images/ic_logo.ico")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_field = new javax.swing.JTextField();
        chk_but = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Quiz");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Java was release in which year ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 290, 30));

        txt_field.setToolTipText("answer");
        txt_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(txt_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, 40));

        chk_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beginner/images/chk.png"))); // NOI18N
        chk_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_butActionPerformed(evt);
            }
        });
        getContentPane().add(chk_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, 60));

        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beginner/images/ic_qb.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_butActionPerformed
        // TODO add your handling code here:
        if (txt_field.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No answer provided !");
        } else {
            if (txt_field.getText().equalsIgnoreCase("1995")) {
                JOptionPane.showMessageDialog(null, "Congrat.");
                txt_field.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Try Again.");
                txt_field.setText(null);
            }
    }//GEN-LAST:event_chk_butActionPerformed

    }
    private void txt_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simple_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simple_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simple_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simple_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simple_Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chk_but;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_field;
    // End of variables declaration//GEN-END:variables
}
